---
permalink: administration/reference_parameters_to_set_up_netapp_management_console_data_protection_capability.html 
sidebar: sidebar 
keywords: parameter, netapp, management, console, protection, capability, ntap, update, set, backup, format 
summary: Per configurare la funzionalità di protezione dei dati di NetApp Management Console sono necessari diversi parametri. 
---
= Parametri per impostare la funzionalità di protezione dei dati di NetApp Management Console
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per configurare la funzionalità di protezione dei dati di NetApp Management Console sono necessari diversi parametri.

|===
| Parametro | Impostazione | Descrizione 


 a| 
NTAP_PM_UPDATE
 a| 
(Y
| N) 


 a| 
Consente di attivare e disattivare l'aggiornamento della funzionalità di protezione dei dati di NetApp Management Console che registra le copie Snap Creator Snapshot nella funzionalità di protezione dei dati di NetApp Management Console. *Nota:* se NTAP_PM_UPDATE è abilitato, è necessario configurare NTAP_DFM_DATA_SET.
 a| 
NTAP_DFM_DATA_SET
 a| 



 a| 
Elenca i sistemi storage e i set di dati delle funzionalità di protezione dei dati di NetApp Management Console in base alle correlazioni dei volumi, ovvero controller1:datet1/vol1,vol2;controller1:datet2/vol3.
 a| 
NTAP_PM_RUN_BACKUP
 a| 
(Y



| N)  a| 
Avvia il backup della funzionalità di protezione dei dati di NetApp Management Console, verifica l'avanzamento e lo stato e attende il completamento.
 a| 
NTAP_DFM_SNAPSHOT_FORMAT

|===