---
permalink: administration/task_setting_snap_creator_server_credentials.html 
sidebar: sidebar 
keywords: snap, creator, server, credentials, scadmin, port 
summary: 'È possibile memorizzare le credenziali di Snap Creator Server (come nome host del server o indirizzo IP, porta, utente e password) per evitare di inserire più volte le credenziali nell"interfaccia della riga di comando (CLI). Se necessario, è possibile rimuovere le credenziali memorizzate.' 
---
= Impostazione delle credenziali di Snap Creator Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile memorizzare le credenziali di Snap Creator Server (come nome host del server o indirizzo IP, porta, utente e password) per evitare di inserire più volte le credenziali nell'interfaccia della riga di comando (CLI). Se necessario, è possibile rimuovere le credenziali memorizzate.

La procedura per impostare le credenziali di Snap Creator Server è la stessa per Windows e UNIX. La seguente procedura utilizza esempi dell'ambiente UNIX.

. Sull'host in cui è installato Snap Creator Server, immettere il seguente comando dalla directory di installazione di Snap Creator Server:
+
`/install_path/scServer4.3/snapcreator --credentials`

+
Viene visualizzato il seguente output che consente di impostare le credenziali predefinite per il server Snap Creator:

+
[listing]
----
Enter user: SCadmin

Enter password:

Enter Snap Creator server hostname or IP [localhost]:
Enter Snap Creator server port [8443]:
Enter Profile name ( or * for any profile: *
Enter Config name ( or * for any config: *
----
. Inserire le informazioni appropriate per ciascuna voce.
+
Dopo aver immesso il nome di configurazione, le credenziali vengono salvate e viene visualizzato il seguente messaggio: INFO: CLI credentials stored successfully (INFORMAZIONI: Credenziali CLI memorizzate correttamente). Le credenziali vengono memorizzate nel file snapcreator.credentials nella directory o nella cartella .snapcreatornella home directory.

. Se si desidera rimuovere le credenziali memorizzate, eliminare il file snapcreator.credentials.

