---
permalink: administration/task_customizing_the_default_keystore.html 
sidebar: sidebar 
keywords: keystore, certificate, keytool, windows, unix 
summary: È possibile personalizzare il keystore o il certificato predefinito utilizzando il comando keytool disponibile su Windows e UNIX. 
---
= Personalizzazione del keystore predefinito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile personalizzare il keystore o il certificato predefinito utilizzando il comando keytool disponibile su Windows e UNIX.

Il comando keytool è fornito da Java. In alcuni ambienti, potrebbe essere necessario passare alla directory di installazione Java per eseguire il comando keytool.

Snap Creator non supporta i truststore.

. Arrestare l'agente Snap Creator.
. Generare un nuovo keystore con un singolo certificato:
+
`keytool -genkeypair -alias alias_name -keystore keystore_file -keypass private_key_password -storepass keystore_password`

+
Keytool -genkeypair -alias servicekey -keystore serviceKeystore.jks -keypass kypswd123 -storepass kystrpswd123

. Copiare il file keystore nella directory scAgent4.3.0/etc/.
. Aggiornare I parametri KEYSTORE_FILE=keystore_file e KEYSTORE_PASS=keystore password nel file di configurazione di Snap Creator Agent (scAgent4.3.0/etc/allowed_comands.config).
. Avviare Snap Creator Agent.


*Informazioni correlate*

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_windows.adoc[Avvio, verifica e interruzione di Snap Creator Agent su Windows]

xref:task_starting_verifying_and_stopping_the_snap_creator_agent_on_unix.adoc[Avvio, verifica e interruzione di Snap Creator Agent su UNIX]
