---
permalink: installation/task_starting_the_server_from_a_command_prompt.html 
sidebar: sidebar 
keywords: starting, start, server, command, prompt 
summary: 'È possibile avviare manualmente Snap Creator Server da un prompt dei comandi eseguendo uno script batch (scServer.bat).' 
---
= Avvio del server da un prompt dei comandi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile avviare manualmente Snap Creator Server da un prompt dei comandi eseguendo uno script batch (scServer.bat).

In genere, seguire questa procedura solo se non è stata selezionata l'opzione *Avvia server come servizio* durante l'installazione.

È inoltre possibile pianificare l'esecuzione dello script batch (scServer.bat) all'avvio tramite il Task Scheduler di Windows. Per ulteriori informazioni sull'utilizzo di Task Scheduler di Windows, consultare la documentazione relativa al sistema operativo Windows in uso.

Poiché lo script batch (scServer.bat) esegue Snap Creator in primo piano, Snap Creator Server continua a essere eseguito solo finché il prompt dei comandi è aperto. La chiusura del prompt dei comandi chiude Snap Creator Server. Per l'esecuzione in background, è necessario utilizzare il servizio Snap Creator Server.

. Aprire un prompt dei comandi e immettere i seguenti comandi:
+
[listing]
----
cd \install_path\scServerrelease-version\bin\
scServer.bat start
----
+
[listing]
----
cd \Program Files\NetApp\Snap_Creator_Framework\scServer4.1.0\bin\
scServer.bat start
----

