---
permalink: installation/task_upgrading_snap_creator_server_4_1_x_on_unix_based_systems.html 
sidebar: sidebar 
keywords: upgrading, upgrade, snap, creator, server, 4.1.x, unix, unix-based 
summary: 'È possibile eseguire l"aggiornamento da Snap Creator Server 4.1.x su sistemi basati su UNIX.' 
---
= Aggiornamento di Snap Creator Server 4.1.x su sistemi basati su UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire l'aggiornamento da Snap Creator Server 4.1.x su sistemi basati su UNIX.

* I processi di Snap Creator sono stati interrotti prima di eseguire il backup delle directory di Snap Creator per garantire che i dati di cui è stato eseguito il backup siano completi.
+
Ad esempio, immettere i seguenti comandi:

+
[listing]
----
/install_path/scServer4.1.0/bin/scServer stop
/install_path/scAgent4.1.0/bin/scAgent stop
----
* È stato eseguito il backup delle seguenti directory e di tutte le sottodirectory e i file associati all'interno della sottodirectory del motore di Snap Creator 4.1.x Server (/install_path/scServer4.1.x/Engine):
+
** Database di Snap Creator (../snapcreator)
** Proprietà del server Snap Creator (../etc)
** File di configurazione (../configs)
** Log (../logs)
** Repository di plug-in, se attivato (../snapcreatorPlugin) *Nota:* non è necessario eliminare le copie di backup di Snap Creator 4.1.x create.




I percorsi descritti di seguito fanno riferimento al percorso di installazione predefinito. Le informazioni sul percorso potrebbero differire dal percorso di installazione se non vengono utilizzate le impostazioni predefinite.

Una volta completato il processo di aggiornamento, è necessario considerare i seguenti problemi:

* Se il database Snap Creator aggiornato contiene alcune attività contrassegnate come "`in corso`", lo stato rimane invariato anche dopo il completamento del processo di aggiornamento.
* L'amministratore predefinito nell'ultima versione di Snap Creator deve essere un amministratore in Snap Creator 4.1.x.
+
Se l'utente 4.1.x non è un amministratore, l'aggiornamento assegna un ruolo operatore all'utente 4.1.x.

+
.. Interrompere i processi di Snap Creator se non è già stato fatto.
+
Per informazioni sull'interruzione dei processi, fare riferimento ai dettagli forniti in precedenza in questo argomento.

.. Installare la versione più recente di Snap Creator, ma non avviare Snap Creator Server.
+
Per ulteriori informazioni, vedere le informazioni sull'installazione di Snap Creator Server su UNIX.

.. Copiare la directory del database Snap Creator 4.1.x di cui è stato eseguito il backup nella posizione più recente in /install_path/scServer4.1.x/Engine/snapcreator.
.. Copiare la directory di configurazione 4.1.x di cui è stato eseguito il backup nella posizione più recente in /install_path/scServer4.1.x/Engine/configs).
.. Copiare la directory dei log di backup 4.1.x nella posizione più recente in /install_path/scServer4.1.x/Engine/logs.
.. Modificare le directory nella sottodirectory del motore nel percorso di installazione di Snap Creator in /install_path/scServer4.1.x/Engine.
.. Aggiornare Snap Creator immettendo il seguente comando: java -jar snapcreator.jar -upgrade




Una volta completato il processo di aggiornamento, avviare Snap Creator Server immettendo il seguente comando:

[listing]
----
/install_path/scServer4.1.x/bin/scServer start
----
Inoltre, eliminare la directory di installazione di Snap Creator 4.1.x.


IMPORTANT: Non eliminare le copie di backup finché non si è certi di non dover ripristinare una versione precedente.

È inoltre necessario convalidare l'avvio della GUI di Snap Creator Framework accedendo all'host locale sulla porta specificata (https://IP_address:gui_port[]).

È necessario connettersi utilizzando HTTPS; in caso contrario, la connessione non viene automaticamente reindirizzata a una connessione HTTPS e la GUI non funziona.
