---
permalink: installation/task_installing_the_snap_creator_agent_on_unix.html 
sidebar: sidebar 
keywords: installing, install, snap, creator, agent, unix 
summary: 'Snap Creator Agent viene eseguito su qualsiasi piattaforma di sistemi aperti (AIX, HP-UX, Linux e Solaris).' 
---
= Installazione di Snap Creator Agent su sistemi basati su UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snap Creator Agent viene eseguito su qualsiasi piattaforma di sistemi aperti (AIX, HP-UX, Linux e Solaris).

È necessario installare JRE 1.8 Update 72 o versione successiva. Per ulteriori informazioni, consultare i link correlati all'installazione di Java sui server Snap Creator.

La persona che esegue l'installazione deve disporre di diritti di accesso e privilegi sufficienti.

La porta predefinita per Snap Creator Agent è 9090. Utilizzare netstat o uno strumento simile per verificare che la porta di rete (9090 o la porta che si desidera utilizzare) sia disponibile e non sia già in uso (ad esempio, immettere: `netstat -nap | grep 9090`).

Snap Creator dovrebbe essere già stato scaricato. Per ulteriori informazioni, consulta le informazioni sul download del software Snap Creator.

Linux viene utilizzato come piattaforma di esempio.

. Copiare il file Snap Creator tar.gz scaricato nella posizione in cui si desidera installare Snap Creator Agent.
+

NOTE: Se si intende utilizzare il plug-in IBM Domino, selezionare una posizione diversa dalla cartella dei dati Domino.

+
.. Per creare una sottodirectory, immettere il seguente comando con il nome della directory:
+
[listing]
----
mkdir snap_creator_directory
----
+
[listing]
----
mkdir /SC_41
----
.. Copiare il file Snap Creator tar.gz nella directory appena creata immettendo il seguente comando:
+
[listing]
----
cp NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
/snap_creator_directory
----
+
[listing]
----
cp NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
/SC_41
----


. Passare alla directory in cui si trova il file .tar di Snap Creator Framework ed estrarre il file immettendo i seguenti comandi:
+

NOTE: A seconda dell'ambiente UNIX, potrebbe essere necessario decomprimere il file prima di immettere il comando tar.

+
[listing]
----
cd snap_creator_directory
tar -xvf NetApp_Snap_Creator_Frameworkrelease-os.tar.gz
----
+
** Snap_creator_directory è la posizione in cui verrà installato Snap Creator.
** La release è la release corrente del pacchetto software Snap Creator.
** il sistema operativo è il sistema operativo.
+
[listing]
----
cd /sc_41
tar -xvf NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz
----


+
In questo modo si estraggono sia il software Server che il software Agent. In genere, viene configurato solo il server Snap Creator. Gli agenti risiedono normalmente nel database o nei server di applicazioni da proteggere, come illustrato nell'esempio seguente:

+
+

+
[listing]
----
NetApp_Snap_Creator_Framework4.1.0-Linux32.tar.gz  scServer4.1.0
scAgent4.1.0
----
. Immettere i seguenti comandi e rispondere alle istruzioni visualizzate nell'esempio per configurare Snap Creator Agent.
+
[listing]
----
cd scAgent*
./snapcreator --setup
Welcome to the NetApp Snap Creator Framework release-version!
\#\#\# Installation options \#\#\#
01. NetApp Snap Creator Framework release-version Agent
Select install option (enter a number or "q" to quit): <Enter 01>

END USER LICENSE AGREEMENT
<...the EULA displays...>

Do you accept the End User License Agreement (y|n): <Enter y>

Enter Snap Creator server port [9090]: <Enter agent port>

INFO: Updated NetApp Snap Creator Framework release-version
/install_path/scAgentrelease-version/engine/etc/agent.properties


INFO: To start scAgent please do the following:

/install_path/scAgentrelease-version/bin/scAgent start
----
. Avviare Snap Creator Agent:
+
[listing]
----
/install_path/scAgentrelease-version/bin/scAgent start
----
+

NOTE: Per eseguire l'agente Snap Creator automaticamente all'avvio, aggiungere il comando start a uno script.

+
Le istruzioni per creare uno script variano leggermente a seconda del sistema operativo utilizzato e delle preferenze dell'amministratore di sistema che gestisce il server. In genere, il comando start per Snap Creator Agent può essere aggiunto a un file che inizia con S9 (ad esempio, S99scAgent) che si trova nella sottodirectory /path/to/rc2.d. La sottodirectory rc2.d si trova generalmente in /etc/, ma può dipendere dal sistema operativo host e dalla particolare configurazione del server. Per ulteriori informazioni, consultare la documentazione del sistema operativo in uso.

+
Viene visualizzato il seguente messaggio:

+
[listing]
----
Starting scAgent:
    Watchdog: Running
       Agent: Running
----


*Informazioni correlate*

xref:task_installing_java_on_snap_creator_hosts.adoc[Installazione di Java su host Snap Creator]

xref:task_downloading_the_snap_creator_software.adoc[Download del software Snap Creator]
