---
permalink: domino-ops/task_performing_point_in_time_volume_restore.html 
sidebar: sidebar 
keywords: domino, ibm, volume, restore 
summary: È possibile utilizzare il plug-in IBM Domino per eseguire ripristini di volume point-in-time, up-to-the-minute o up-to-the-minute selezionabili per tutti i principali tipi di storage. 
---
= Esecuzione di un ripristino del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il plug-in IBM Domino per eseguire ripristini di volume point-in-time, up-to-the-minute o up-to-the-minute selezionabili per tutti i principali tipi di storage.

Assicurarsi di:

* Impostare la directory di ripristino dei dati nel file di configurazione sulla directory dei dati Domino.
* Arrestare il server Domino.


Le opzioni di ripristino del volume sono le seguenti:

|===
| Tipo di ripristino | Descrizione 


 a| 
Ripristino del volume (point-in-time)
 a| 
Ripristina lo stato dell'intero volume al momento della copia Snapshot.



 a| 
Ripristino del volume (up-to-the-minute)
 a| 
Ripristina lo stato dell'intero volume al momento della copia Snapshot, quindi riproduce i registri delle transazioni Domino nella copia più recente.



 a| 
Ripristino del volume (selezionabile fino al minuto)
 a| 
Ripristina lo stato dell'intero volume al momento della copia Snapshot, quindi riproduce i registri delle transazioni Domino a un orario specificato.

|===

NOTE: Per ripristini point-in-time up-to-the-minute e selezionabili, è necessario attivare la registrazione delle transazioni Domino.

I registri delle transazioni possono essere riprodotti solo in avanti. Se si seleziona un orario prima della creazione della copia Snapshot, si verifica un errore di ripristino.

. Nel riquadro profili e configurazioni, selezionare il file di configurazione e fare clic su *azioni* > *Ripristina*.
+
Selezionando *Restore* viene avviata automaticamente la procedura guidata di ripristino di Snap Creator Framework. Durante la procedura guidata di ripristino, fare clic su *Avanti* per passare alla pagina successiva. Fare clic su *Indietro* per tornare alla pagina precedente.

+

NOTE: Se si esegue il ripristino da una copia SnapVault, viene richiesto di eseguire il ripristino dallo storage primario o secondario. La scelta dipende dalla modalità di gestione della limitazione descritta in link:concept_domino_database_restore_overview.html["Ripristino dei database"].

. Nella pagina Restore details (Dettagli ripristino), specificare i dettagli del ripristino:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Nome controller/Vserver
 a| 
Selezionare la SVM sul sistema di storage da cui si desidera eseguire il ripristino.



 a| 
Ripristinare il nome del volume
 a| 
Selezionare il volume da cui si desidera eseguire il ripristino.



 a| 
Policy
 a| 
Selezionare il criterio per il backup da cui si desidera eseguire il ripristino.



 a| 
Copie Snap Creator Snapshot/tutte le copie Snapshot
 a| 
Lasciare l'impostazione predefinita.



 a| 
Ripristinare il nome della copia Snapshot
 a| 
Selezionare la copia Snapshot da cui si desidera eseguire il ripristino.



 a| 
Tipo di ripristino
 a| 
Selezionare *Volume Restore* (Ripristino volume).

|===
. Nella pagina seguente, specificare il tipo di ripristino del volume:
+
|===
| Per questo campo... | Eseguire questa operazione... 


 a| 
Tipo di ripristino
 a| 
Fare clic sul tipo di ripristino del volume. Se si sceglie *selezionabile fino al minuto*, vengono visualizzati nuovi campi in cui è possibile specificare la data e l'ora in cui si desidera riprodurre i registri delle transazioni Domino. Fare clic su *Ignora convalida* se l'ora sul server Snap Creator non corrisponde all'ora sul controller dello storage.



 a| 
Disattivare la replica
 a| 
Selezionare questa casella per impostare un nuovo ID replica Domino per i file di database ripristinati.

|===
. Esaminare il riepilogo e fare clic su *fine*.
. Nella finestra di dialogo Volume Restore (Ripristino volume), fare clic su *OK*.
+
Snap Creator avvia il processo di ripristino. Le informazioni sul lavoro vengono visualizzate nel pannello Console.



Al termine dell'operazione di ripristino, riavviare il server Domino.
